# Generated by Django 4.2.10 on 2024-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0004_response_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='killmail_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='killmail_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
