# Generated by Django 4.2.14 on 2024-08-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0004_alter_general_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access the view payouts table app'), ('use_access', 'Can access, use and therefore request reimbursements.'), ('fcing_access', 'Can access the fleet command module to create srp links and view them'), ('reimbursement_access', 'Can access the reimbursement module to accept, reject, and delete srp requests, as well as view statistics'), ('admin_access', 'Can force to recalculate the view payouts table'))},
        ),
    ]
