# Generated by Django 4.2.10 on 2024-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0005_request_killmail_hash_alter_request_killmail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='killmail_region_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='killmail_region_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='killmail_solar_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='killmail_time',
            field=models.DateTimeField(),
        ),
    ]
