# Generated by Django 4.2.14 on 2024-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0005_alter_general_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killmail_id', models.IntegerField(unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
