# Generated by Django 4.2.10 on 2024-04-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0006_request_killmail_region_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
