# Generated by Django 4.2.14 on 2024-08-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0006_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killmail_id', models.IntegerField(unique=True)),
                ('status', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('handler_character_id', models.IntegerField(default=0)),
                ('handler_character_name', models.CharField(max_length=255)),
                ('handler_corporation_id', models.IntegerField(default=0)),
                ('handler_corporation_name', models.CharField(max_length=255)),
                ('handler_alliance_id', models.IntegerField(default=0)),
                ('handler_alliance_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='alliance_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='alliance_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='broadcast',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='character_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='character_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='corporation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='corporation_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='killmail_hash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='ship_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='ship_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='srp_response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='srppayouts.srp'),
        ),
    ]
