# Generated by Django 4.2.10 on 2024-04-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0007_request_requester_id_request_requester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='submitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
