# Generated by Django 4.2.14 on 2024-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0007_srp_request_alliance_id_request_alliance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='killmail_hash',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
