# Generated by Django 4.2.14 on 2024-08-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0008_alter_request_killmail_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='alliance_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='broadcast',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='character_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='corporation_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='killmail_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='ship_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='srp_response',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='srppayouts.srp'),
        ),
    ]
