# Generated by Django 4.2.10 on 2024-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0008_request_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
