# Generated by Django 4.2.14 on 2024-08-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0009_alter_request_alliance_name_alter_request_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='srp_response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='srppayouts.srp'),
        ),
    ]
