# Generated by Django 4.2.14 on 2024-08-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0010_alter_request_srp_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='srp_response',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='srppayouts.srp'),
        ),
    ]
