# Generated by Django 4.2.14 on 2024-08-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0012_alter_request_srp_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='srp_response',
        ),
    ]
