# Generated by Django 4.2.14 on 2024-08-09 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0013_remove_request_srp_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='killmail_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
