# Generated by Django 4.2.14 on 2024-08-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0014_request_killmail_time_request_requested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='killmail_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
