# Generated by Django 4.2.14 on 2024-08-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0016_alter_request_killmail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='killmail_time',
            field=models.DateTimeField(),
        ),
    ]
