# Generated by Django 4.2.14 on 2024-08-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0017_alter_request_killmail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='constellation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='constellation_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='region_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='region_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='system_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='system_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
