# Generated by Django 4.2.14 on 2024-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0018_request_constellation_id_request_constellation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.CharField(default='', max_length=255),
        ),
    ]
