# Generated by Django 4.2.14 on 2024-08-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0019_request_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='srppayouts.srp'),
        ),
    ]
