# Generated by Django 4.2.14 on 2024-08-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0020_request_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='killmail_amount',
            field=models.IntegerField(default=0),
        ),
    ]
