# Generated by Django 4.2.14 on 2024-08-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0021_request_killmail_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srp',
            name='killmail_id',
        ),
    ]
