# Generated by Django 4.2.14 on 2024-08-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0022_remove_srp_killmail_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srp',
            old_name='status',
            new_name='reimbursement',
        ),
    ]
