# Generated by Django 4.2.14 on 2024-08-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srppayouts', '0023_rename_status_srp_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srp',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
